version: '3'
services:
  app:
    image: makeshift/pavlok_telegram_bot
    build: .
    restart: always
    container_name: "pavlok_telegram_bot"
    env_file:
      - .env
    labels:
      - proxy.hosts=pavlok.makeshift.ninja,pavlok.local.makeshift.ninja,pavlok.public.makeshift.ninja
      - proxy.port=80
      - proxy.isPublic
    networks:
      - web
    volumes:
      - ./db.json:/usr/src/app/db.json
networks:
  web:
    external: true
